#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "tableaunoir"
name = "Tableaunoir"
description.en = "Online blackboard with magnets for teaching and making animations and presentations"
description.fr = "Tableau noir en ligne avec aimants pour enseigner, créer des animations et des présentations"

version = "2026.03.11~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "GPL-3.0"
website = "https://tableaunoir.github.io/"
demo = "https://tableaunoir.github.io/"
code = "https://github.com/tableaunoir/tableaunoir"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/tableaunoir"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/tableaunoir/tableaunoir/archive/a319dbe8e14d1042025a3cf974872e6c1ea77a97.tar.gz"
    sha256 = "35d4fe5cd7abb7d46ad016720e2fca033ee59d1c2a359127353e4ff3f80ecf0f"

    autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"
    
    [resources.permissions]
    main.url = "/"
